version: "3.9"

services:

  server:
    container_name: spring_news_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./src/main/resources/static:/src/main/resources/static

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: newsapp
      MYSQL_ROOT_PASSWORD: 123

    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
