INSERT INTO article (tag_id, author_id, article_title, article_content, article_date, picture_link)
VALUES
       (1, 4, '"Это не фотошоп" - Свидетели гор Краснодарского края', '
Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo dicta fuga, officia excepturi animi porro, consequuntur ab, voluptate nisi repellendus sit explicabo vitae rem! Asperiores perferendis tempora sit explicabo laboriosam. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores repellat voluptatem dignissimos asperiores officiis iste saepe, at dolor voluptates, repudiandae necessitatibus. Odio quis voluptas hic id amet veritatis laudantium a. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur nam, recusandae qui, adipisci laborum vitae odio inventore nostrum porro, dolorum culpa itaque? Voluptatibus nemo cumque, officia nobis magnam
doloremque dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam error sed soluta, neque doloribus, blanditiis omnis pariatur unde tempora excepturi voluptates perspiciatis debitis possimus adipisci corrupti, labore accusantium rerum fugit? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illum aspernatur, ex quos obcaecati blanditiis maiores inventore eveniet officia ipsa reiciendis eaque quis consectetur necessitatibus repellendus voluptatibus nulla odit cupiditate tenetur?
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Provident optio placeat consequatur. Expedita facere temporibus perferendis odit veritatis quod assumenda itaque minima dolor, nihil voluptates, saepe omnis eligendi debitis repellat? Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, magnam blanditiis. Incidunt, tempore laudantium modi saepe, quisquam quidem facere molestias, cupiditate non ab pariatur? Tempora, reprehenderit. Cumque quibusdam nam facilis!
', DATE(NOW()), 'mountain.jpg'),
       (3, 2, 'Панда в Московском зоопарке вкусно покушала и легла спать', '...2', DATE(NOW() - interval 2 day), 'panda.png'),
       (2, 3, 'Очередной парк снесут и построят в Москве', '...3', DATE(NOW() - interval 1 day), 'park_renovation.png'),
       (4, 1, 'В России разработают технологию автоматического анализа состояния кожи', '...4', DATE(NOW() - interval 1 day), 'microscope.jpg'),
       (2, 2, 'Церковь в районе Восточное Измайлово откроют в конце весны', '...5', DATE(NOW() - interval 1 day), 'church.png'),
       (1, 1, 'Запущена новая нефтедобывающая вышка в Сибири', '...6', DATE(NOW()), 'worker.jpg'),
       (4, 3, 'Российские ученые обнаружили новое семейство магнитов', '...7', DATE(NOW()), 'scientist.jpg');